#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Backing up app files..."
ynh_backup "$install_dir"

ynh_print_info "Backing up data directory..."
ynh_backup "$data_dir"

ynh_print_info "Backing up PostgreSQL database..."
ynh_psql_dump_db > db.sql

ynh_print_info "Backup complete!"
