#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Updating BASE_PATH in .env..."
ynh_config_add --template="app.env" --destination="$install_dir/.env"
chmod 600 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

ynh_print_info "Updating nginx configuration..."
ynh_config_add_nginx

ynh_print_info "Restarting service..."
ynh_systemctl --service="$app" --action="restart" --wait_until="Listening on"

ynh_print_info "URL change complete!"
