#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Restoring app files..."
ynh_restore "$install_dir"

ynh_print_info "Restoring data directory..."
ynh_restore "$data_dir"

ynh_print_info "Restoring PostgreSQL database..."
ynh_psql_db_shell < "${YNH_CWD}/db.sql"

install_nodejs
install_node_deps

chown -R "$app:$app" "$install_dir"
chown -R "$app:$app" "$data_dir"

ynh_config_add_nginx
ynh_config_add_systemd

ynh_systemctl --service="$app" --action="enable"
ynh_systemctl --service="$app" --action="start" --wait_until="Listening on" --log_path="systemd"

ynh_print_info "Restore complete!"
